import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-white/80 backdrop-blur sticky top-0 z-10">
          <div className="max-w-5xl mx-auto flex items-center justify-between px-4 py-3">
            <Link href="/" className="font-bold text-orange-600">
              Rolling Bites
            </Link>
            <ul className="flex space-x-4">
              <li>
                <Link href="/about" className="hover:text-orange-600">
                  About
                </Link>
              </li>
              <li>
                <Link href="/menu" className="hover:text-orange-600">
                  Menu
                </Link>
              </li>
              <li>
                <Link href="/locations" className="hover:text-orange-600">
                  Locations
                </Link>
              </li>
              <li>
                <Link href="/events" className="hover:text-orange-600">
                  Events
                </Link>
              </li>
              <li>
                <Link href="/contact" className="hover:text-orange-600">
                  Contact
                </Link>
              </li>
            </ul>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
